name: CI

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main", "feature/**", "hotfix/**" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: build-and-test
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (LTS)
        uses: actions/setup-node@v4
        with:
          node-version: 20            # стабильнее, чем 22
          # ВАЖНО: не используем cache: 'yarn', чтобы он не дергал Yarn 1

      - name: Enable Corepack & use Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate
          yarn --version

      # (опционально) кэш Yarn Berry
      - name: Cache Yarn (Berry)
        uses: actions/cache@v4
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci

      - name: Build
        run: yarn build
